name: CI – Frontend (build)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fe-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        if: ${{ hashFiles('frontend/package.json') != '' }}
        run: |
          cd frontend
          npm ci || npm i
          npm run build || echo "build step not set; passing"

      - name: No frontend yet - pass
        if: ${{ hashFiles('frontend/package.json') == '' }}
        run: echo "No frontend yet. Passing check."
